### ISSUE TITLE
module 'tensorflow.contrib.rnn.python.ops.rnn_cell' has no attribute '_linear'

### ISSUE THREAD

**Issue by pkl625** [da03/Attention-OCR#71]
File "......./attention-OCR-master/src/model/seq2seq.py", line 75, in <module>
    linear = rnn_cell._linear # pylint: disable=protected-access

**Comment by liudq521** [comment]
tensorflow-1.4

**Comment by EzequielAdrianM** [comment]
Use tensorflow 1.2 or lower.

**Comment by masonsun** [comment]
The API for Tensorflow has changed in more recent versions. To fix this, edit `src/model/seq2seq.py` by

1. Changing `linear = rnn_cell._linear` to `linear = core_rnn_cell._linear` (line 73)
2. Including the import `from tensorflow.contrib.rnn.python.ops import core_rnn_cell`

Hope that helps!

**Comment by pkl625** [comment]
thanks all! 
use tensorflow-gpu==1.4

- [ 1 ] change

 `from tensorflow.contrib.rnn.python.ops import rnn, rnn_cell` to `from tensorflow.python.ops import rnn_cell_impl`  

- [ 2 ]  change `rnn_cell._linear`  to  `rnn_cell_impl._linear` 

it works!

**Comment by balajiwix** [comment]
CNN outdim: (?, ?, 512)
Traceback (most recent call last):
  File "src/launcher.py", line 146, in <module>
    main(sys.argv[1:], exp_config.ExpConfig)
  File "src/launcher.py", line 142, in main
    session = sess)
  File "E:\Data_Science\OCR\Attention-OCR-master\src\model\model.py", line 151, in __init__
    use_gru = use_gru)
  File "E:\Data_Science\OCR\Attention-OCR-master\src\model\seq2seq_model.py", line 87, in __init__
    single_cell = tf.contrib.rnn.core_rnn_cell.BasicLSTMCell(attn_num_hidden, forget_bias=0.0, state_is_tuple=False)
AttributeError: module 'tensorflow.contrib.rnn' has no attribute 'core_rnn_cell'


Please help me on, solving this issue

**Comment by kulkarnivishal** [comment]
replace : 
single_cell = tf.contrib.rnn.core_rnn_cell.BasicLSTMCell(attn_num_hidden, forget_bias=0.0, state_is_tuple=False)
with : 
tf.contrib.rnn.BasicLSTMCell(attn_num_hidden, forget_bias=0.0, state_is_tuple=False)

**Comment by famunir** [comment]
Some following changes may have to be made after performing the aforementioned changes:
In _seq2seq_model.py_ make following changes as well:

1) Replace 
_cell = tf.contrib.rnn.core_rnn_cell.MultiRNNCell([single_cell] * attn_num_layers, state_is_tuple=False)_
With
_cell = tf.contrib.rnn.MultiRNNCell([single_cell] * attn_num_layers, state_is_tuple=False)_
2) Replace
_lstm_fw_cell = tf.contrib.rnn.core_rnn_cell.BasicLSTMCell(num_hidden, forget_bias=0.0, state_is_tuple=False)_
With
_lstm_fw_cell = tf.contrib.rnn.BasicLSTMCell(num_hidden, forget_bias=0.0, state_is_tuple=False)_
3) Replace
_lstm_bw_cell = tf.contrib.rnn.core_rnn_cell.BasicLSTMCell(num_hidden, forget_bias=0.0, state_is_tuple=False)_
With
_lstm_bw_cell = tf.contrib.rnn.BasicLSTMCell(num_hidden, forget_bias=0.0, state_is_tuple=False)_
Hope it helps!

**Comment by pkl625** [comment]
> The API for Tensorflow has changed in more recent versions. To fix this, edit `src/model/seq2seq.py` by
> 
> 1. Changing `linear = rnn_cell._linear` to `linear = core_rnn_cell._linear` (line 73)
> 2. Including the import `from tensorflow.contrib.rnn.python.ops import core_rnn_cell`
> 
> Hope that helps!

thanks itworks

**Comment by jameswan** [comment]
I did the changes above, but I get this error:

Traceback (most recent call last):
  File "src/launcher.py", line 146, in <module>
    main(sys.argv[1:], exp_config.ExpConfig)
  File "src/launcher.py", line 142, in main
    session = sess)
  File "G:\Attention-OCR-master\src\model\model.py", line 151, in __init__
    use_gru = use_gru)
  File "G:\Attention-OCR-master\src\model\seq2seq_model.py", line 92, in __init__
    cell = single_cell
UnboundLocalError: local variable 'single_cell' referenced before assignment

**Comment by AKhileshPothuri** [comment]
> The API for Tensorflow has changed in more recent versions. To fix this, edit `src/model/seq2seq.py` by
> 
> 1. Changing `linear = rnn_cell._linear` to `linear = core_rnn_cell._linear` (line 73)
> 2. Including the import `from tensorflow.contrib.rnn.python.ops import core_rnn_cell`
> 
> Hope that helps!

This really helped...thanks :)

**Comment by Lanme** [comment]
if x.shape.ndims is None:
AttributeError: '_Linear' object has no attribute 'shape'

**Comment by mamingjie-China** [comment]
> thanks all!
> use tensorflow-gpu==1.4
> 
> * [ 1 ] change
> 
> `from tensorflow.contrib.rnn.python.ops import rnn, rnn_cell` to `from tensorflow.python.ops import rnn_cell_impl`
> 
> * [ 2 ]  change `rnn_cell._linear`  to  `rnn_cell_impl._linear`
> 
> it works!

It doesn't work in tensorflow-gpu==1.14...

**Comment by AshutoshUpadhya** [comment]
> Some following changes may have to be made after performing the aforementioned changes:
> In _seq2seq_model.py_ make following changes as well:
> 
> 1. Replace
>    _cell = tf.contrib.rnn.core_rnn_cell.MultiRNNCell([single_cell] * attn_num_layers, state_is_tuple=False)_
>    With
>    _cell = tf.contrib.rnn.MultiRNNCell([single_cell] * attn_num_layers, state_is_tuple=False)_
> 2. Replace
>    _lstm_fw_cell = tf.contrib.rnn.core_rnn_cell.BasicLSTMCell(num_hidden, forget_bias=0.0, state_is_tuple=False)_
>    With
>    _lstm_fw_cell = tf.contrib.rnn.BasicLSTMCell(num_hidden, forget_bias=0.0, state_is_tuple=False)_
> 3. Replace
>    _lstm_bw_cell = tf.contrib.rnn.core_rnn_cell.BasicLSTMCell(num_hidden, forget_bias=0.0, state_is_tuple=False)_
>    With
>    _lstm_bw_cell = tf.contrib.rnn.BasicLSTMCell(num_hidden, forget_bias=0.0, state_is_tuple=False)_
>    Hope it helps!

Thanks! It helped

**Comment by AshutoshUpadhya** [comment]
A complete list of changes including @mamingjie-China and @masonsun :--
1.  In file seq2seq.py
change  linear = rnn_cell._linear to linear = core_rnn_cell._linear **(line 73)**
             import from tensorflow.contrib.rnn.python.ops import core_rnn_cell

2. in  file seq2seq_model.py
Replace cell = tf.contrib.rnn.core_rnn_cell.MultiRNNCell([single_cell] * attn_num_layers, state_is_tuple=False)
With
cell = tf.contrib.rnn.MultiRNNCell([single_cell] * attn_num_layers, state_is_tuple=False)
Replace
lstm_fw_cell = tf.contrib.rnn.core_rnn_cell.BasicLSTMCell(num_hidden, forget_bias=0.0, state_is_tuple=False)
With
lstm_fw_cell = tf.contrib.rnn.BasicLSTMCell(num_hidden, forget_bias=0.0, state_is_tuple=False)
Replace
lstm_bw_cell = tf.contrib.rnn.core_rnn_cell.BasicLSTMCell(num_hidden, forget_bias=0.0, state_is_tuple=False)
With
lstm_bw_cell = tf.contrib.rnn.BasicLSTMCell(num_hidden, forget_bias=0.0, state_is_tuple=False)

**Comment by jb1812** [comment]
![image](https://user-images.githubusercontent.com/104253332/164961758-97a1128a-2e3c-402b-b8e9-143b72182cfc.png)
![image](https://user-images.githubusercontent.com/104253332/164962128-5b3a955f-65f0-49f1-8642-3f017cda89ce.png)

what could be done to resolve this

**Comment by pkl625** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，我将尽快给你回复。谢谢~
